name: book-store

services:
    book-store-mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: book-store-mssql 
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=#8YourStrong@Password123!
            - MSSQL_PID=Developer
        volumes:
            - book-store-mssql-data:/var/storages/book-store-mssql

    book-store-redis:
        image: redis:8.10.1
        container_name: book-store-redis
        ports:
            - "6379:6379"
        volumes:
            - book-store-cache-data:/var/storages/book-store-cache

networks:
    book-store-network:
        name: book-store-network

volumes:
    book-store-mssql-data:
    book-store-cache-data:
        